name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.2'

    - name: Run tests
      run: | 
        for exercise in $(find . -name '*_test.py' -printf '%h\n' | sort -u); do
            echo "Running tests for $exercise..."
            pushd $exercise
            pytest
            popd
        done
